### ISSUE TITLE
Option to force update sensor values

### ISSUE THREAD

**Issue by OneGoogus** [Baldhor/Homey-ESPhome-Enhanced#14]
Hi Baldhor

Would it be possible to make an option in settings on the device to update values every so often?
Like this:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/2384481/d3104892-fb73-4fb3-a2be-98c12782e086)

its becouse I post a line every day in a Google Sheet on devices with no communication the last 24 hours.
And the esp device is the only thing jumping on it becouse values have been the same the past 3 days.
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/2384481/280b0623-0096-42f8-8d17-f3fad6f9de58)

**Comment by Baldhor** [comment]
@OneGoogus For me the best would be to force publish from the device itself.

Add this to your sensor configuration:
```
    filters:
      - timeout: 24h
```

Your device will send a nan value if there was no update for 24h.
However to be honest I don't think Homey app will appreciate a NAN value :)


Another solution is to use a timer, and periodically send the current value.
```
time:
  - platform: sntp
    # ...
    on_time:
      # Every morning at 7am
      - seconds: 0
        minutes: 0
        hours: 7
        then:
          - lambda: !lambda |-
            id(<yourdeviceid>).internal_send_state_to_frontend(id(<yourdeviceid>.state);
```
I'm 99% sure this solution will work as long as you fix the syntax errors (if any) => untested
