### ISSUE TITLE
Adding a Sonoff Basic through the Wizard is not working - Could not connect to the device, or something went wrong

### ISSUE THREAD

**Issue by JoachimVeulemans** [Baldhor/Homey-ESPhome-Enhanced#17]
**Describe the bug**
Adding a Sonoff Basic through the Wizard is not working.

**To Reproduce**
1. Flash firmware to Sonoff Basic
2. Install ESPhome app in Homey
3. Add device, add ip, standard port, add password
4. See error "Could not connect to the device, or something went wrong"

**Expected behavior**
The device should be added without errors.

**Screenshots**
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/32447944/c509b465-2ed4-4638-b802-88e9ae614f13)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/32447944/a8a08f81-9d61-4304-a207-5be129e20210)

**Additional context**
```
esphome:
  name: sonoffbasic
  comment: "Sonoff001"

esp8266:
  board: esp8285

logger:

api:
  password: !secret ota_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH # for ESP8266 LOW/HIGH are mixed up, esphome/issues/issues/1532
  ap:
    ssid: ${devicename}
    password: !secret wifi_password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret ota_password

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
```
