### ISSUE TITLE
Can not connect to device

### ISSUE THREAD

**Issue by JoachimVeulemans** [Baldhor/Homey-ESPhome-Enhanced#20]
**Describe the bug**
Sorry for the spam of problems but I am still experiencing some issues.

When I try to add Shelly or Sonoff basic devices (one virtual device), everthing is working. When I try to create a custom esp with multiple virtual devices, I am now stuck at the first step. After entering the ip, port & password, it does not connect to the device.

Another bug I have found is when a device goes offline (due to power/wifi issues) and comes back online, it is no longer accessible in Homey. When I try to reconnect (add new device -> update existing), it is still not responding. A solution that I have found is to restart the ESPhome app in Homey. After the restart, the device is back accessible until the next power/wifi issue.

**Screenshots**
![Scherm­afbeelding 2023-08-19 om 15 25 22](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/32447944/94531f77-1508-4364-ac65-0660df4879fb)
![Scherm­afbeelding 2023-08-19 om 15 26 25](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/32447944/feb6bb95-34a8-466c-b954-2b7b7d066eb5)

**Comment by Baldhor** [comment]
@JoachimVeulemans The connection is refused:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/1011d554-74bb-42af-9743-8988a2dcf771)

I don't know why but the Object is like "empty", but it means an error from the physical device (like if password was incorrect).

Possible to check on logs on the device side (webserver) ? And maybe share the yaml?


For my test, I use a device with a yml configuration including over 20 differents entities, so I don't think it is the problem.


NB I still fixed this bug on the way:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/b497d61d-149a-494e-8fdb-98b47190bab7)
(but I think you don't care lol)

**Comment by Baldhor** [comment]
@JoachimVeulemans did you configure the logger in your yml ?
```
# Enable logging
logger:
  baud_rate: 0
  level: DEBUG #(by default)
```

**Comment by Baldhor** [comment]
@JoachimVeulemans are you using password or encryption key for the concerned device?
I will add support for encryption key (probably today).

**Comment by JoachimVeulemans** [comment]
Hi @Baldhor yes, I checked the config earlier, I was using an encryption key. Completely look over it... I have removed the encryption key, it is working now. Might re-add it when you support it.

The problem of the reboot is still present. I have to restart the app to regain control.

Also, cover devices are not showing up in the virtual capabilities. Is this not supported yet?

**Comment by JoachimVeulemans** [comment]
Also for the cover, I have no open/closed sensor for the gate within the same physical device.

I have an open/closed sensor connected to Homey. It would be great if I could update the status of the cover when the state of the sensor changes.

Thanks.

**Comment by Baldhor** [comment]
@JoachimVeulemans
encryption key => implemented, I'm testing :)
Cover => main device I use, so yes it is fully supported, including tilt

**Comment by JoachimVeulemans** [comment]
The cover is not showing up in the virtual capabilities. Anything wrong in my config?

Also, one small improvement, I have a sensor for the Wi-Fi signal but the capability is missing in the list. I have picked measure_pressure, but it is not entirely correct.
<img width="421" alt="Scherm­afbeelding 2023-08-20 om 14 02 42" src="https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/32447944/b650a597-03a3-4b29-9f7d-b60214466b7b">

Config:
```
esphome:
  name: REDACTED
  platform: ESP8266
  board: d1_mini
  comment: "RelayBoard001"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: ${devicename}
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: REDACTED
    password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

cover:
  - platform: template
    name: "Garage Door"
    open_action:
      # Cancel any previous action
      - switch.turn_off: garagepoort_trigger
      # Turn the OPEN switch on briefly
      - switch.turn_on: garagepoort_trigger
      - delay: 0.3s
      - switch.turn_off: garagepoort_trigger
    close_action:
      # Cancel any previous action
      - switch.turn_off: garagepoort_trigger
      # Turn the OPEN switch on briefly
      - switch.turn_on: garagepoort_trigger
      - delay: 0.3s
      - switch.turn_off: garagepoort_trigger
    optimistic: true
    assumed_state: true

switch:
  - platform: gpio
    pin:
      number: D3
      inverted: true
    name: "Garagepoort"
    id: garagepoort_trigger
```
