### ISSUE TITLE
The cover is not showing up in the list of unbind native capabilities. Anything wrong in my config?

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#22]
The cover is not showing up in the list of unbind native capabilities. Anything wrong in my config?

Also, one small improvement, I have a sensor for the Wi-Fi signal but the capability is missing in the list. I have picked measure_pressure, but it is not entirely correct.
<img width="421" alt="Scherm­afbeelding 2023-08-20 om 14 02 42" src="https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/32447944/b650a597-03a3-4b29-9f7d-b60214466b7b">

Config:
```
esphome:
  name: REDACTED
  platform: ESP8266
  board: d1_mini
  comment: "RelayBoard001"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: ${devicename}
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: REDACTED
    password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

cover:
  - platform: template
    name: "Garage Door"
    open_action:
      # Cancel any previous action
      - switch.turn_off: garagepoort_trigger
      # Turn the OPEN switch on briefly
      - switch.turn_on: garagepoort_trigger
      - delay: 0.3s
      - switch.turn_off: garagepoort_trigger
    close_action:
      # Cancel any previous action
      - switch.turn_off: garagepoort_trigger
      # Turn the OPEN switch on briefly
      - switch.turn_on: garagepoort_trigger
      - delay: 0.3s
      - switch.turn_off: garagepoort_trigger
    optimistic: true
    assumed_state: true

switch:
  - platform: gpio
    pin:
      number: D3
      inverted: true
    name: "Garagepoort"
    id: garagepoort_trigger
```

_Originally posted by @JoachimVeulemans in https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/20#issuecomment-1685266910_
