### ISSUE TITLE
Slimmelezer ESP device keeps crashing periodically

### ISSUE THREAD

**Issue by RoadXY** [Baldhor/Homey-ESPhome-Enhanced#35]
**Describe the bug**
Slimmelezer ESP device keeps crashing periodically

**Device type**
Custom device by Marcel Zuidwijk.
Bought here: https://www.zuidwijk.com/product/slimmelezer-plus/

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/c123cefa-ee62-4752-a185-bfd34196d623)

**YAML file**
```
substitutions:
  device_name: slimmelezer
    
esphome:
  name: ${device_name}
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false

wifi:
  ap:
    ssid: ${device_name}
  
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 1700

dsmr:
  id: dsmr_instance
  max_telegram_length: 1700
  gas_mbus_id: 1
  request_interval: 30s

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
    gas_delivered:
      name: "Gas Consumed"

  - platform: wifi_signal
    name: "WiFi Signaal"
    id: wifi_signalstrength
    update_interval: 900s
    icon: 'mdi:signal'
    
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    internal: true
    update_interval: 600s
    icon: 'mdi:clock-outline'
    filters:
      - lambda: return x / 60;
    unit_of_measurement: "min"

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
```
