### ISSUE TITLE
Request: Support for climate components, Panasonic heat pump

### ISSUE THREAD

**Issue by Nettopp** [Baldhor/Homey-ESPhome-Enhanced#42]
Thank you for a very interesting project on adding ESPhome to Homey, your work is appreciated!

As described on the Homey forum, I will add a file with the log for items not showing up in the app under "native capabilities".
Currently, when adding the ESPhome connected to the heat pump, the following options are available:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/120424963/9ae197e2-8391-445a-a86c-4ad5e0dff63f)

Please see the attached file for "newentity" from the log.
The following objects are included in the file:

panasonic_ac_outside_temperature
panasonic_ac_power_consumption
panasonic_ac_econavi_switch
panasonic_ac 
panasonic_ac_horizontal_swing_mode
panasonic_ac_vertical_swing_mode

At the bottom of the file I also added an "Unhandled entity type", as it looks like the "panasonic_ac" objectID contains several parameters, as seen in the screenshot below: supportsCurrentTemperature, supportedModesList, supportedCustomFanModesList, supportedCustomPresetsList

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/120424963/fec4f6ef-77c8-406a-9956-d2211243fcf0)

If you want to see the console.re it is running at the moment: https://console.re/nettoppesp
[console re newobject.txt](https://github.com/Baldhor/Homey-ESPhome-Enhanced/files/12618499/console.re.newobject.txt)

**Comment by Baldhor** [comment]
@Nettopp Thx for the logs!

So your device has 6 entities, only 3 of them appear in the wizard:
- panasonic_ac_outside_temperature
- panasonic_ac_power_consumption
- panasonic_ac_econavi_switch

It's missing 3 entities, which we will focus on:
- panasonic_ac => Climate, it has many differents attributs
- panasonic_ac_horizontal_swing_mode => Select 
- panasonic_ac_vertical_swing_mode => Select


What follow is a todo list ... and it's a long one :)
In **bold** what is required for your usage.


### **panasonic_ac**
```
{
    "_events": {},
    "_eventsCount": 1,
    "config": {
        "objectId": "panasonic_ac",
        "key": 290099816,
        "name": "Panasonic AC",
        "uniqueId": "panasonic-acclimatepanasonic_ac",
        "supportsCurrentTemperature": true,
        "supportsTwoPointTargetTemperature": false,
        "supportedModesList": [
            0,
            1,
            2,
            3,
            4,
            5
        ],
        "visualMinTemperature": 16,
        "visualMaxTemperature": 30,
        "visualTargetTemperatureStep": 0.5,
        "legacySupportsAway": false,
        "supportsAction": false,
        "supportedFanModesList": [],
        "supportedSwingModesList": [
            0,
            1,
            2,
            3
        ],
        "supportedCustomFanModesList": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "Automatic"
        ],
        "supportedPresetsList": [],
        "supportedCustomPresetsList": [
            "Normal",
            "Powerful",
            "Quiet"
        ],
        "disabledByDefault": false,
        "icon": "",
        "entityCategory": 0,
        "visualCurrentTemperatureStep": 0.5
    },
    "type": "Climate",
    "name": "Panasonic AC",
    "id": 290099816,
}
```
The entity expose lot of things:
- **visualMinTemperature/visualMaxTemperature** : impact target_temperature attributes
- **visualTargetTemperatureStep** : step for target_temperature
- **visualCurrentTemperatureStep** : precision of current temperature
- **current_temperature**: getable only
- supportsTwoPointTargetTemperature: getable only (config)
- **target_temperature**: getable/setable
- target_temperature_low: getable/setable
- target_temperature_high: getable/setable
- **mode**: getable/setable, list of values is unclear, need to check if there are constants defined
- **supportedModesList**: getable, restrict available mode values
- fan_mode: getable/setable, list of values is unclear, need to check if there are constants defined
- supportedFanModesList: getable, restrict available fan_mode values
- swing_mode: getable/setable, list of values is unclear, need to check if there are constants defined
- supportedSwingModesList: getable, restrict available swing_mode values
- custom_fan_mode: ...
- supportedCustomFanModesList: ...
- preset: ...
- supportedPresetsList: ...
- custom_preset: ...
- supportedCustomPresetsList: ...

### **panasonic_ac_horizontal_swing_mode**
```
{
    "_events": {},
    "_eventsCount": 1,
    "config": {
        "objectId": "panasonic_ac_horizontal_swing_mode",
        "key": 3166509394,
        "name": "Panasonic AC Horizontal Swing Mode",
        "uniqueId": "panasonic-acselectpanasonic_ac_horizontal_swing_mode",
        "icon": "",
        "optionsList": [
            "auto",
            "left",
            "left_center",
            "center",
            "right_center",
            "right"
        ],
        "disabledByDefault": false,
        "entityCategory": 0
    },
    "type": "Select",
    "name": "Panasonic AC Horizontal Swing Mode",
    "id": 3166509394,
}
```
**In homey, it should match to an enum capability, which will require a custom capability of type enum with the values set during initialization.
Should be getable and setable.**


### **panasonic_ac_vertical_swing_mode**
```
{
    "_events": {},
    "_eventsCount": 1,
    "config": {
        "objectId": "panasonic_ac_vertical_swing_mode",
        "key": 3804174560,
        "name": "Panasonic AC Vertical Swing Mode",
        "uniqueId": "panasonic-acselectpanasonic_ac_vertical_swing_mode",
        "icon": "",
        "optionsList": [
            "swing",
            "auto",
            "up",
            "up_center",
            "center",
            "down_center",
            "down"
        ],
        "disabledByDefault": false,
        "entityCategory": 0
    },
    "type": "Select",
    "name": "Panasonic AC Vertical Swing Mode",
    "id": 3804174560,
}
```
**In homey, it should match to an enum capability, which will require a custom capability of type enum with the values set during initialization.
Should be getable and setable.**

**Comment by Baldhor** [comment]
For reference your yaml file:
```
esphome:
  name: panasonic-ac
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "xx"
  password: "xx"

logger:
  level: DEBUG
#  baud_rate: 0 # ESP8266 only

api:

ota:

# mqtt:
#  broker: 192.168.1.102

web_server:
  port: 80

# Requires ESPHome 1.15.0+ for the even parity option
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  parity: EVEN

external_components:
  source: github://DomiStyle/esphome-panasonic-ac
  components: [panasonic_ac]


climate:
  - platform: panasonic_ac
    # For CZ-TACG1
    type: cnt

    # For DNSK-P11
    # type: wlan

    name: Panasonic AC
    horizontal_swing_select:
      name: Panasonic AC Horizontal Swing Mode
    vertical_swing_select:
      name: Panasonic AC Vertical Swing Mode
    outside_temperature:
      name: Panasonic AC Outside Temperature

    # Enable as needed
    # eco_switch:
    #   name: Panasonic AC Eco Switch
    econavi_switch:
      name: Panasonic AC Econavi Switch
    # nanoex_switch:
    #   name: Panasonic AC NanoeX Switch
    # mild_dry_switch:
    #   name: Panasonic AC Mild Dry Switch
    current_power_consumption:
      name: Panasonic AC Power Consumption

    # Useful when the ac does not report a current temperature (CZ-TACG1 only)
    # current_temperature_sensor: temperature_sensor_id
```
