### ISSUE TITLE
[BUG] Device becomes unavailable

### ISSUE THREAD

**Issue by priknr1** [Baldhor/Homey-ESPhome-Enhanced#93]
**Describe the bug**
I am using ESPhome to readout and control my Haier Airco.  All functions work well. But after a while (I dont know yet if this is hours or days)  the device becomes unavailable in homey.   
I can then still go to the devices webbrowser page with my phone, so the device is actually still connected to my network and running.

When I restart the ESPhome app, the device is available again. So it seems as some sort of timeout in the ESPhome app.
perhaps a small script running every min, to check device status, and re-establish connection when it is lost?

**To Reproduce**
1 Start app
2. wait

**Expected behavior**
Stay connected forever

**Comment by basnahuis** [comment]
Same problem Here 
![IMG_1469](https://github.com/user-attachments/assets/a99d2a04-8b39-4827-ba84-ed432ca0c7e1)

**Comment by basnahuis** [comment]
@Baldhor Do you have any idea when you can look at this? He now stops er a few hours.

**Comment by andersruneson** [comment]
Hi
Care to share your ESPhome config? I've had my ESPhome connected to Homey for weeks (I'm not running Haier Airco).

**Comment by basnahuis** [comment]
Hello, 
what exactly do you mean by sharing configuration? I've searched but can't find anything to export or something like that. 

I use a Mitsubishi air conditioner. 

The problem is that the app itself cannot connect. I also have a connection to the ESPhome module via Home Assistant, which continues to work without any problems. 

I have created a diagnostic report in the homey, can you do something with that?

Diagnostic report ID: 94ac2a3d-393e-4060-b1d9-eacee0369d27

**Comment by andersruneson** [comment]
> Hello, what exactly do you mean by sharing configuration? I've searched but can't find anything to export or something like that.

I assume you have an ESP device running ESPhome? And then you have a configuration for that device similar to this:

```
esphome:
  name: ttgo
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "MySSID"
  password: "MyPassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testfloorheater Fallback Hotspot"
    password: "burQN9rt0522"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

```

**Comment by basnahuis** [comment]
ah I understand you now. I do not have a configuration overview for this module. I received the module from someone. 

Can I also take it out via USB?

I built it into the air conditioner, so I have to take it out first.

**Comment by andersruneson** [comment]
I don't think you can get it out via USB, but you should ask the person who gave you the module. 
And are you sure you have good enough WiFi reception on the module? 
If you had the configuration and can update the module OTA you could add below and make Homey-ESPhome read those capabilities to log some issues.
```
sensor:
  - platform: uptime
    name: "Uptime"
  - platform: wifi_signal
    name: "RSSI"
    update_interval: 60s

```
